// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/portfolio/Editorial.tsx": () => import("../components/mockups/portfolio/Editorial.tsx"),
  "./components/mockups/portfolio/Structured.tsx": () => import("../components/mockups/portfolio/Structured.tsx")
};
